### ISSUE TITLE
Some issues on your code

### ISSUE THREAD

**Issue by choiyunseok** [adf1178/PT4Code#7]
Thank you for presenting a good paper and sharing the code.

I have read your paper and analyzed the code, and I have a few questions.

1. In the paper, it is explained that PLM is frozen and prefix tuning is done, as the title of the paper is "No more Finetuning". However, in line 195 of "PT4Code/summarization/prompt_t5.py", if freeze_plm is set to False, is it fine-tuning that also trains the parameters of the PLM? In the experiment, it seems to be compared with Fine-tuning and Fine-tuning with Prompt template added.

2. In Table 2 of the paper, the Beam size is mentioned as 10. However, in line 481 of "PT4Code/summarization/prompt_t5.py", beam_size is not passed as an argument value to "_, output_sentence = model.generate(batch)", so it seems that beam_size is not used. If beam_size is added, there will be a significant difference from the results in the paper's table.

3. I have implemented code translation, but the training parameters are not mentioned in the paper or the README.md of github, so the performance in the paper cannot be implemented. Can you share the training parameters for all tasks?

Thank you.

**Comment by adf1178** [comment]
Thanks for your interest in our work!

For Q1: Our experiments are in the full data setting, thus we must tune the whole model with the prefix prompt. For fine-tuning and prompt tuning, we both tune the model. The difference is that we also tune the soft tokens in the prefix prompt.

For Q2: The beam_size arg is modified because I want to increase the inference speed. In the experiments in the paper, the beam size is set to 10.

For Q3: For code translation task, when I implement code translation with openprompt. I met a bug that may cause unexpected truncation. Thus, we use another code base of LmBuff to implement the code translation.

**Comment by choiyunseok** [comment]
Thank you for the quick and kind response.

What is the truncation bug mentioned in Q3?

I seem to be experiencing a similar bug.

For example, the EM (Exact Match) between gold and prediction is different because the tokenized words are different.

Can you give some examples?

Thank you.

**Comment by adf1178** [comment]
The truncation bug is that only short code snippets can be generated entirely but the longer ones will be truncated. I don't know whether this bug is fixed in the latest version :(
